{
 "title": "ERC20 Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transaction Failures",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transaction_failures{instance=\"metrics-exporter:3000\", job=\"SmartContract\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_gas_used{instance=\"metrics-exporter:3000\", job=\"SmartContract\"}"
    }
   ]
  },
  {
   "title": "Contract Interactions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "contract_interactions{instance=\"metrics-exporter:3000\", job=\"SmartContract\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}