global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'SmartContract'
    metrics_path: /metrics
    static_configs:
      - targets: ['metrics-exporter:3000']

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
